In [1]:
import warnings
warnings.filterwarnings('ignore')
import json
import pandas as pd
from config import db_password
from sqlalchemy import create_engine
from datetime import datetime, timedelta, date

In [2]:
# GET Tabled input

# creating database engine
db_name = 'Company_Stock_DB'
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/{db_name}"
engine = create_engine(db_string)

# read data from PostgreSQL database table and load into Dataframe instance
stock_df = pd.read_sql("select * from \"company_all_star\"", engine);

#sort the dataframe by ticker column
stock_df.sort_values(by=['ticker'])

# Print the DataFrame
#pd.set_option('display.max_rows', None)
stock_df.head()

,ticker,date_val,company_name,company_url,employee_count,revenue,sector,city_name,state_name,region,...,latitude,longitude,open_val,high_val,low_val,close_val,volume,volume_weight,number_of_transactions,percent_change
0,AMD,2020-03-12,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,...,37.233325,-121.684635,42.20,43.91,39.60,43.90,86689681.0,41.6701,381223.0,4.028436
1,AMD,2020-03-15,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,...,37.233325,-121.684635,39.08,43.37,38.51,38.71,84545868.0,41.0812,374962.0,0.946776
2,AMD,2020-03-16,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,...,37.233325,-121.684635,40.19,42.88,38.30,41.88,92741881.0,41.1240,434519.0,4.205026
3,AMD,2020-03-17,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,...,37.233325,-121.684635,39.54,41.95,36.75,39.12,106949287.0,39.6363,591862.0,1.062215
4,AMD,2020-03-18,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,...,37.233325,-121.684635,39.56,41.70,37.69,39.82,88939024.0,40.2337,396388.0,0.657230

In [3]:
# preserve date column as type object
#stock_df['date'] = stock_df['date_val']

# have the user enter beginning date as yyyy-mm-dd
begin_date = '2022-01-10'
# have the user enter ending date as yyyy-mm-dd
end_date = '2022-03-10'

# convert the date to datetime64
stock_df['date_val'] = pd.to_datetime(stock_df['date_val'], format='%Y-%m-%d')

begin_df = stock_df.loc[(stock_df['date_val'] >= begin_date)]
end_df = stock_df.loc[(stock_df['date_val'] <= end_date)]

# drop date_val
begin_df.drop(['date_val'], axis=1, inplace=True)
end_df.drop(['date_val'], axis=1, inplace=True)

begin_df.reset_index(drop=True,inplace=True)
begin_df.head()

,ticker,company_name,company_url,employee_count,revenue,sector,city_name,state_name,region,country_code,latitude,longitude,open_val,high_val,low_val,close_val,volume,volume_weight,number_of_transactions,percent_change
0,AMD,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,133.450,138.9900,131.59,137.31,77153906.0,136.1279,499284.0,2.892469
1,AMD,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,138.585,140.5700,135.77,137.47,69669598.0,138.0222,458692.0,0.804560
2,AMD,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,139.440,141.2500,131.81,132.74,76618059.0,135.7041,535482.0,4.804934
3,AMD,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,131.680,137.0000,131.43,136.88,71078438.0,135.0553,466893.0,3.948967
4,AMD,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,134.500,136.3893,131.59,131.93,56589456.0,133.7456,426778.0,1.910781

In [4]:
end_df.reset_index(drop=True,inplace=True)
end_df.head()

,ticker,company_name,company_url,employee_count,revenue,sector,city_name,state_name,region,country_code,latitude,longitude,open_val,high_val,low_val,close_val,volume,volume_weight,number_of_transactions,percent_change
0,AMD,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,42.20,43.91,39.60,43.90,86689681.0,41.6701,381223.0,4.028436
1,AMD,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,39.08,43.37,38.51,38.71,84545868.0,41.0812,374962.0,0.946776
2,AMD,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,40.19,42.88,38.30,41.88,92741881.0,41.1240,434519.0,4.205026
3,AMD,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,39.54,41.95,36.75,39.12,106949287.0,39.6363,591862.0,1.062215
4,AMD,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,39.56,41.70,37.69,39.82,88939024.0,40.2337,396388.0,0.657230

In [5]:
# merge together the beginning and ending dataframes
merged_df = pd.merge(begin_df, end_df, left_index=True, right_index=True)
merged_df

,ticker_x,company_name_x,company_url_x,employee_count_x,revenue_x,sector_x,city_name_x,state_name_x,region_x,country_code_x,...,latitude_y,longitude_y,open_val_y,high_val_y,low_val_y,close_val_y,volume_y,volume_weight_y,number_of_transactions_y,percent_change_y
0,AMD,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,...,37.233325,-121.684635,42.20,43.91,39.600,43.90,86689681.0,41.6701,381223.0,4.028436
1,AMD,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,...,37.233325,-121.684635,39.08,43.37,38.510,38.71,84545868.0,41.0812,374962.0,0.946776
2,AMD,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,...,37.233325,-121.684635,40.19,42.88,38.300,41.88,92741881.0,41.1240,434519.0,4.205026
3,AMD,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,...,37.233325,-121.684635,39.54,41.95,36.750,39.12,106949287.0,39.6363,591862.0,1.062215
4,AMD,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,...,37.233325,-121.684635,39.56,41.70,37.690,39.82,88939024.0,40.2337,396388.0,0.657230
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4279,ZS,Zscaler Inc,zscaler.com,1k-5k,100m-200m,Technology,San Jose,CA,W,US,...,40.262570,-80.187280,395.71,395.71,379.225,385.38,431244.0,384.8870,16100.0,2.610498
4280,ZS,Zscaler Inc,zscaler.com,1k-5k,100m-200m,Technology,San Jose,CA,W,US,...,40.262570,-80.187280,387.52,395.20,383.010,394.43,350994.0,391.7881,12501.0,1.783134
4281,ZS,Zscaler Inc,zscaler.com,1k-5k,100m-200m,Technology,San Jose,CA,W,US,...,40.262570,-80.187280,398.95,407.78,398.950,403.60,485909.0,404.2643,14403.0,1.165560
4282,ZS,Zscaler Inc,zscaler.com,1k-5k,100m-200m,Technology,San Jose,CA,W,US,...,40.262570,-80.187280,405.14,407.37,402.765,404.61,376352.0,404.8678,12237.0,0.130819
4283,ZS,Zscaler Inc,zscaler.com,1k-5k,100m-200m,Technology,San Jose,CA,W,US,...,40.262570,-80.187280,402.93,405.61,394.020,394.27,320142.0,398.0831,12581.0,2.149257

In [6]:
# calculate the absolute value of the diffence in the beginning percentage change and the ending percentage change
merged_df['percent_change_difference'] = abs(merged_df['percent_change_y'] - merged_df['percent_change_x'])
merged_df

,ticker_x,company_name_x,company_url_x,employee_count_x,revenue_x,sector_x,city_name_x,state_name_x,region_x,country_code_x,...,longitude_y,open_val_y,high_val_y,low_val_y,close_val_y,volume_y,volume_weight_y,number_of_transactions_y,percent_change_y,percent_change_difference
0,AMD,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,...,-121.684635,42.20,43.91,39.600,43.90,86689681.0,41.6701,381223.0,4.028436,1.135967
1,AMD,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,...,-121.684635,39.08,43.37,38.510,38.71,84545868.0,41.0812,374962.0,0.946776,0.142215
2,AMD,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,...,-121.684635,40.19,42.88,38.300,41.88,92741881.0,41.1240,434519.0,4.205026,0.599908
3,AMD,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,...,-121.684635,39.54,41.95,36.750,39.12,106949287.0,39.6363,591862.0,1.062215,2.886752
4,AMD,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,...,-121.684635,39.56,41.70,37.690,39.82,88939024.0,40.2337,396388.0,0.657230,1.253551
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4279,ZS,Zscaler Inc,zscaler.com,1k-5k,100m-200m,Technology,San Jose,CA,W,US,...,-80.187280,395.71,395.71,379.225,385.38,431244.0,384.8870,16100.0,2.610498,7.898764
4280,ZS,Zscaler Inc,zscaler.com,1k-5k,100m-200m,Technology,San Jose,CA,W,US,...,-80.187280,387.52,395.20,383.010,394.43,350994.0,391.7881,12501.0,1.783134,0.609987
4281,ZS,Zscaler Inc,zscaler.com,1k-5k,100m-200m,Technology,San Jose,CA,W,US,...,-80.187280,398.95,407.78,398.950,403.60,485909.0,404.2643,14403.0,1.165560,3.009283
4282,ZS,Zscaler Inc,zscaler.com,1k-5k,100m-200m,Technology,San Jose,CA,W,US,...,-80.187280,405.14,407.37,402.765,404.61,376352.0,404.8678,12237.0,0.130819,1.622823
4283,ZS,Zscaler Inc,zscaler.com,1k-5k,100m-200m,Technology,San Jose,CA,W,US,...,-80.187280,402.93,405.61,394.020,394.27,320142.0,398.0831,12581.0,2.149257,2.532764

In [7]:
# drop all *_y's
merged_df.drop(columns = ["ticker_y", "company_name_y", "company_url_y", "employee_count_y", "revenue_y", "sector_y", "city_name_y", "state_name_y", "region_y", "country_code_y", "latitude_y", "longitude_y", "open_val_y", "high_val_y", "low_val_y", "close_val_y", "volume_y", "volume_weight_y", "number_of_transactions_y", "percent_change_y"], axis=1, inplace=True)

In [8]:
merged_df

,ticker_x,company_name_x,company_url_x,employee_count_x,revenue_x,sector_x,city_name_x,state_name_x,region_x,country_code_x,...,longitude_x,open_val_x,high_val_x,low_val_x,close_val_x,volume_x,volume_weight_x,number_of_transactions_x,percent_change_x,percent_change_difference
0,AMD,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,...,-121.684635,133.450,138.9900,131.59,137.31,77153906.0,136.1279,499284.0,2.892469,1.135967
1,AMD,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,...,-121.684635,138.585,140.5700,135.77,137.47,69669598.0,138.0222,458692.0,0.804560,0.142215
2,AMD,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,...,-121.684635,139.440,141.2500,131.81,132.74,76618059.0,135.7041,535482.0,4.804934,0.599908
3,AMD,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,...,-121.684635,131.680,137.0000,131.43,136.88,71078438.0,135.0553,466893.0,3.948967,2.886752
4,AMD,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,...,-121.684635,134.500,136.3893,131.59,131.93,56589456.0,133.7456,426778.0,1.910781,1.253551
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4279,ZS,Zscaler Inc,zscaler.com,1k-5k,100m-200m,Technology,San Jose,CA,W,US,...,-121.890583,228.370,229.9700,204.36,204.37,4379337.0,210.5799,72096.0,10.509261,7.898764
4280,ZS,Zscaler Inc,zscaler.com,1k-5k,100m-200m,Technology,San Jose,CA,W,US,...,-121.890583,203.500,203.9200,190.13,198.63,4389634.0,196.9284,71180.0,2.393120,0.609987
4281,ZS,Zscaler Inc,zscaler.com,1k-5k,100m-200m,Technology,San Jose,CA,W,US,...,-121.890583,203.840,213.5700,199.12,212.35,3050554.0,209.3268,45960.0,4.174843,3.009283
4282,ZS,Zscaler Inc,zscaler.com,1k-5k,100m-200m,Technology,San Jose,CA,W,US,...,-121.890583,212.130,213.5100,204.87,208.41,2305091.0,208.7971,40754.0,1.753642,1.622823
4283,ZS,Zscaler Inc,zscaler.com,1k-5k,100m-200m,Technology,San Jose,CA,W,US,...,-121.890583,211.020,211.6700,200.50,201.14,1893573.0,202.9376,37307.0,4.682021,2.532764

In [9]:
merged_df.set_index("company_name_x").head()

,ticker_x,company_url_x,employee_count_x,revenue_x,sector_x,city_name_x,state_name_x,region_x,country_code_x,latitude_x,longitude_x,open_val_x,high_val_x,low_val_x,close_val_x,volume_x,volume_weight_x,number_of_transactions_x,percent_change_x,percent_change_difference
company_name_x,,,,,,,,,,,,,,,,,,,,
Advanced Micro Devices Inc,AMD,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,133.450,138.9900,131.59,137.31,77153906.0,136.1279,499284.0,2.892469,1.135967
Advanced Micro Devices Inc,AMD,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,138.585,140.5700,135.77,137.47,69669598.0,138.0222,458692.0,0.804560,0.142215
Advanced Micro Devices Inc,AMD,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,139.440,141.2500,131.81,132.74,76618059.0,135.7041,535482.0,4.804934,0.599908
Advanced Micro Devices Inc,AMD,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,131.680,137.0000,131.43,136.88,71078438.0,135.0553,466893.0,3.948967,2.886752
Advanced Micro Devices Inc,AMD,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,134.500,136.3893,131.59,131.93,56589456.0,133.7456,426778.0,1.910781,1.253551

In [10]:
merged_df['coordinates_x'] = merged_df['latitude_x'].astype('str') + ", " + merged_df['longitude_x'].astype('str')
merged_df.drop(['latitude_x', 'longitude_x'], axis=1, inplace=True)

In [ ]:
merged_df.head()

In [ ]:
month_dict = merged_df.to_dict(orient='records')

month_dict[0]

In [ ]:
# turn into JSON
month_json = json.dumps(month_dict, indent=2)
print(month_json)

In [ ]:
geo_json = json.dumps(geo_dict, indent=3)
print(geo_json)

In [ ]:
with open("../resources/monthly_stocks.json", "w") as outfile:
    outfile.write(geo_json)

In [ ]:
file_path = open("../resources/monthly_stocks.json")
geo_json = json.load(file_path)
geo_json