In [1]:
# KERNEL: mlenv

# Import dependencies
import warnings
warnings.filterwarnings("ignore")

In [2]:
#dependencies
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from imblearn.ensemble import BalancedRandomForestClassifier
from sklearn.model_selection import train_test_split
from sqlalchemy import create_engine
from config import db_password

In [3]:
# GET Tabled input
# creating database engine
db_name = 'Company_Stocks_DB'
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/{db_name}"
engine = create_engine(db_string)
# read data from PostgreSQL database table and load into Dataframe instance
stock_df = pd.read_sql("select * from \"view_company_all_star\"", engine);
# Print the DataFrame
stock_df.head()

,ticker,date_val,company_name,company_url,employee_count,revenue,sector,city_name,state_name,country_code,latitude,longitude,open_val,high_val,low_val,close_val,volume,volume_weight,number_of_transactions,percent_change
0,AMD,2020-03-12,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37.233325,-121.684635,42.20,43.91,39.60,43.90,86689681.0,41.6701,381223.0,4.028436
1,AMD,2020-03-15,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37.233325,-121.684635,39.08,43.37,38.51,38.71,84545868.0,41.0812,374962.0,0.946776
2,AMD,2020-03-16,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37.233325,-121.684635,40.19,42.88,38.30,41.88,92741881.0,41.1240,434519.0,4.205026
3,AMD,2020-03-17,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37.233325,-121.684635,39.54,41.95,36.75,39.12,106949287.0,39.6363,591862.0,1.062215
4,AMD,2020-03-18,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37.233325,-121.684635,39.56,41.70,37.69,39.82,88939024.0,40.2337,396388.0,0.657230

In [4]:
# # Data Load (Test_File)
# stock_df = pd.read_csv("../Queries/Testing_Files/company_all_star.csv")
# stock_df.head(30)

In [5]:
stock_df.columns.tolist()

['ticker',
 'date_val',
 'company_name',
 'company_url',
 'employee_count',
 'revenue',
 'sector',
 'city_name',
 'state_name',
 'country_code',
 'latitude',
 'longitude',
 'open_val',
 'high_val',
 'low_val',
 'close_val',
 'volume',
 'volume_weight',
 'number_of_transactions',
 'percent_change']

In [6]:
# check dtypes
stock_df.dtypes

ticker                     object
date_val                   object
company_name               object
company_url                object
employee_count             object
revenue                    object
sector                     object
city_name                  object
state_name                 object
country_code               object
latitude                  float64
longitude                 float64
open_val                  float64
high_val                  float64
low_val                   float64
close_val                 float64
volume                    float64
volume_weight             float64
number_of_transactions    float64
percent_change            float64
dtype: object

In [10]:
# training model needs to be "int64" for it to be fit, converted all float64s
stock_df[[
    "latitude", 
    "longitude", 
    "open_val", 
    "high_val", 
    "low_val", 
    "close_val", 
    "volume",
    "volume_weight",
    "number_of_transactions",
    "percent_change"]] = stock_df[[
                                "latitude", 
                                "longitude",
                                "open_val", 
                                "high_val", 
                                "low_val", 
                                "close_val", 
                                "volume",
                                "volume_weight",
                                "number_of_transactions",
                                "percent_change"
                                ]].astype("int")

In [12]:
# verify .astype() changes
stock_df.dtypes

ticker                    object
date_val                  object
company_name              object
company_url               object
employee_count            object
revenue                   object
sector                    object
city_name                 object
state_name                object
country_code              object
latitude                   int64
longitude                  int64
open_val                   int64
high_val                   int64
low_val                    int64
close_val                  int64
volume                     int64
volume_weight              int64
number_of_transactions     int64
percent_change             int64
dtype: object

In [13]:
stock_df.head(30)

,ticker,date_val,company_name,company_url,employee_count,revenue,sector,city_name,state_name,country_code,latitude,longitude,open_val,high_val,low_val,close_val,volume,volume_weight,number_of_transactions,percent_change
0,AMD,2020-03-12,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,42,43,39,43,86689681,41,381223,4
1,AMD,2020-03-15,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,39,43,38,38,84545868,41,374962,0
2,AMD,2020-03-16,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,40,42,38,41,92741881,41,434519,4
3,AMD,2020-03-17,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,39,41,36,39,106949287,39,591862,1
4,AMD,2020-03-18,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,39,41,37,39,88939024,40,396388,0
5,AMD,2020-03-19,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,41,42,39,39,106859502,41,533411,4
6,AMD,2020-03-22,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,40,42,38,41,101704663,40,493186,2
7,AMD,2020-03-23,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,44,46,43,46,106794151,45,535460,4
8,AMD,2020-03-24,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,46,47,44,44,93760389,46,488900,4
9,AMD,2020-03-25,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,45,47,45,47,73915608,46,379715,3
10,AMD,2020-03-26,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,46,47,45,46,74599218,47,376711,0
11,AMD,2020-03-29,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,47,48,46,47,68486602,47,346822,1
12,AMD,2020-03-30,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,47,48,45,45,83483749,46,414446,5
13,AMD,2020-03-31,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,44,46,43,43,92083081,44,421006,1
14,AMD,2020-04-01,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,43,45,43,44,79024133,44,368530,2
15,AMD,2020-04-02,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,44,44,41,42,79334966,43,345992,3
16,AMD,2020-04-05,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,44,47,44,47,82293964,46,367010,7
17,AMD,2020-04-06,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,48,49,46,47,102098689,48,456174,2
18,AMD,2020-04-07,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,48,49,47,48,64930779,48,288314,1
19,AMD,2020-04-08,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,49,50,47,48,80357393,49,372619,2
20,AMD,2020-04-12,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,48,51,48,50,64248112,49,315983,5
21,AMD,2020-04-13,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,52,55,52,54,85306750,54,411068,5
22,AMD,2020-04-14,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,53,55,53,54,83814033,54,340554,2
23,AMD,2020-04-15,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,55,58,55,56,103106456,56,444953,1
24,AMD,2020-04-16,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,57,57,55,56,76908783,56,359731,1
25,AMD,2020-04-19,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,55,58,55,56,72367258,57,329989,1
26,AMD,2020-04-20,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,56,57,51,52,123906390,53,603204,6
27,AMD,2020-04-21,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,54,56,54,55,63162386,55,284023,1
28,AMD,2020-04-22,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,56,57,55,55,69648827,56,300001,1
29,AMD,2020-04-23,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,US,37,-121,55,56,54,56,72854752,55,311178,1

In [14]:
# need help with which features are to be used and which to drop

# DROP LONG LAT

In [15]:
# Create our features 
X = stock_df.drop("volume_weight", axis=1)
X = pd.get_dummies(X)

# Target 
y = stock_df["volume_weight"]

In [16]:
# One dataset for geolocation and another for stock behaviour? run each through the model?

In [17]:
X.describe()

,latitude,longitude,open_val,high_val,low_val,close_val,volume,number_of_transactions,percent_change,ticker_AAPL,...,state_name_WA,state_name_WI,country_code_Argentina,country_code_Australia,country_code_CA,country_code_CH,country_code_CN,country_code_Netherlands,country_code_UK,country_code_US
count,50874.000000,50874.000000,50874.000000,50874.000000,50874.000000,50874.000000,5.087400e+04,5.087400e+04,50874.000000,50874.000000,...,50874.000000,50874.000000,50874.000000,50874.000000,50874.000000,50874.000000,50874.000000,50874.000000,50874.000000,50874.000000
mean,37.089063,-90.437846,296.988167,301.174765,292.553426,296.896765,7.683480e+06,7.490834e+04,1.066222,0.009907,...,0.069348,0.009907,0.009907,0.009907,0.009907,0.019814,0.009907,0.019814,0.009907,0.910839
std,11.113165,51.767554,480.529339,486.203403,474.318435,480.192698,1.728108e+07,1.334121e+05,1.564538,0.099040,...,0.254047,0.099040,0.099040,0.099040,0.099040,0.139361,0.099040,0.139361,0.099040,0.284979
min,-34.000000,-122.000000,4.000000,4.000000,4.000000,4.000000,6.954300e+04,2.794000e+03,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,37.000000,-121.000000,82.000000,84.000000,81.000000,82.000000,1.261210e+06,2.208600e+04,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
50%,37.000000,-111.000000,155.000000,158.000000,152.000000,155.000000,2.626642e+06,3.648000e+04,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,41.000000,-77.000000,302.000000,308.000000,298.000000,302.000000,6.403628e+06,6.899325e+04,2.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,52.000000,150.000000,3744.000000,3773.000000,3696.000000,3731.000000,4.016934e+08,2.966979e+06,40.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [18]:
y.value_counts()

53      345
6       318
55      302
54      300
52      292
       ...
2442      1
2379      1
2448      1
2446      1
850       1
Name: volume_weight, Length: 2423, dtype: int64

In [19]:
np.unique(y)

array([   4,    5,    6, ..., 3720, 3721, 3722])

In [20]:
# train the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [21]:
# random forest classfier
# n_estimator default at 100
random_forest = BalancedRandomForestClassifier(n_estimators=100, random_state=1)
random_forest.fit(X_train, y_train)

BalancedRandomForestClassifier(random_state=1)

In [ ]:
# confusion matrix
# this matrix is gigantic
y_pred = random_forest.predict(X_test)
confusion_matrix(y_test, y_pred)

In [ ]:
balanced_accuracy_score(y_test, y_pred)

In [ ]:
print(classification_report_imbalanced(y_test, y_pred))

In [ ]:
sorted(zip(X.columns, random_forest.feature_importances_), reverse=True)