# METHOD FROM ARTICLE
### https://tinyurl.com/yc4de7rr

In [1]:
#dependencies
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
from sklearn import metrics
#from sklearn.metrics import balanced_accuracy_score
#from imblearn.metrics import classification_report_imbalanced
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sqlalchemy import create_engine
from config import db_password
import psycopg2

In [2]:
# GET Tabled input
# creating database engine
db_name = 'Company_Stocks_DB'
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/{db_name}"
engine = create_engine(db_string)
# read data from PostgreSQL database table and load into Dataframe instance
stock_df = pd.read_sql("select * from \"company_all_star\"", engine);
# sort the dataframe by ticker column
stock_df.sort_values(by=["ticker"])
# Print the DataFrame
stock_df.head()

,ticker,date_val,company_name,company_url,employee_count,revenue,sector,city_name,state_name,region,...,latitude,longitude,open_val,high_val,low_val,close_val,volume,volume_weight,number_of_transactions,percent_change
0,AMD,2020-03-12,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,...,37.233325,-121.684635,42.20,43.91,39.60,43.90,86689681.0,41.6701,381223.0,4.028436
1,AMD,2020-03-15,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,...,37.233325,-121.684635,39.08,43.37,38.51,38.71,84545868.0,41.0812,374962.0,0.946776
2,AMD,2020-03-16,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,...,37.233325,-121.684635,40.19,42.88,38.30,41.88,92741881.0,41.1240,434519.0,4.205026
3,AMD,2020-03-17,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,...,37.233325,-121.684635,39.54,41.95,36.75,39.12,106949287.0,39.6363,591862.0,1.062215
4,AMD,2020-03-18,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,...,37.233325,-121.684635,39.56,41.70,37.69,39.82,88939024.0,40.2337,396388.0,0.657230

In [3]:
stock_df.columns.tolist()

['ticker',
 'date_val',
 'company_name',
 'company_url',
 'employee_count',
 'revenue',
 'sector',
 'city_name',
 'state_name',
 'region',
 'country_code',
 'latitude',
 'longitude',
 'open_val',
 'high_val',
 'low_val',
 'close_val',
 'volume',
 'volume_weight',
 'number_of_transactions',
 'percent_change']

In [4]:
#def get_stock(begin_date, end_date)
 # stock_df['date'] = stock_date['date_val']
 # begin_date = begin_date
 # end_date = end_date 
    #rest of code in cell below
 # for loop

In [5]:
# # preserve date column as type object
# stock_df['date'] = stock_df['date_val']
# # have the user enter beginning date as yyyy-mm-dd
# begin_date = '2022-03-08'
# # have the user enter ending date as yyyy-mm-dd
# end_date = '2022-03-10'
# # Convert the date to datetime64
stock_df['date_val'] = pd.to_datetime(stock_df['date_val'], format='%Y-%m-%d')
# stock_df = stock_df.loc[(stock_df['date_val'] >= begin_date)
#                      & (stock_df['date_val'] <= end_date)]
# # drop throw-aways
# stock_df.drop(["longitude", "latitude", "company_name", "company_url","date_val"], axis=1, inplace=True)
# stock_df

In [6]:
stock_df.drop(['number_of_transactions'], axis=1, inplace=True)
stock_df.head(20)

,ticker,date_val,company_name,company_url,employee_count,revenue,sector,city_name,state_name,region,country_code,latitude,longitude,open_val,high_val,low_val,close_val,volume,volume_weight,percent_change
0,AMD,2020-03-12,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,42.200,43.9100,39.600,43.90,86689681.0,41.6701,4.028436
1,AMD,2020-03-15,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,39.080,43.3700,38.510,38.71,84545868.0,41.0812,0.946776
2,AMD,2020-03-16,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,40.190,42.8800,38.300,41.88,92741881.0,41.1240,4.205026
3,AMD,2020-03-17,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,39.540,41.9500,36.750,39.12,106949287.0,39.6363,1.062215
4,AMD,2020-03-18,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,39.560,41.7000,37.690,39.82,88939024.0,40.2337,0.657230
5,AMD,2020-03-19,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,41.510,42.4825,39.580,39.61,106859502.0,41.2299,4.577210
6,AMD,2020-03-22,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,40.620,42.3200,38.950,41.64,101704663.0,40.7188,2.511078
7,AMD,2020-03-23,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,44.040,46.8100,43.990,46.22,106794151.0,45.7175,4.950045
8,AMD,2020-03-24,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,46.790,47.8750,44.425,44.63,93760389.0,46.5954,4.616371
9,AMD,2020-03-25,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,45.780,47.5000,45.400,47.50,73915608.0,46.7201,3.757099
10,AMD,2020-03-26,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,46.320,47.9750,45.900,46.58,74599218.0,47.1068,0.561313
11,AMD,2020-03-29,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,47.240,48.4600,46.660,47.86,68486602.0,47.8113,1.312447
12,AMD,2020-03-30,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,47.925,48.5300,45.160,45.48,83483749.0,46.9889,5.101721
13,AMD,2020-03-31,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,44.180,46.8500,43.160,43.66,92083081.0,44.9559,1.177003
14,AMD,2020-04-01,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,43.400,45.2800,43.100,44.49,79024133.0,44.2178,2.511521
15,AMD,2020-04-02,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,44.300,44.8393,41.700,42.59,79334966.0,43.0584,3.860045
16,AMD,2020-04-05,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,44.300,47.5800,44.060,47.52,82293964.0,46.0197,7.268623
17,AMD,2020-04-06,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,48.960,49.6500,46.675,47.56,102098689.0,48.2654,2.859477
18,AMD,2020-04-07,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,48.070,49.0000,47.610,48.79,64930779.0,48.4781,1.497816
19,AMD,2020-04-08,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,49.650,50.2500,47.720,48.38,80357393.0,49.2513,2.557905

In [7]:
# get first stock ticker in first row
# process_list = []
# prev_ticker = stock_df.iat[0,0]
# print (prev_ticker)
# i = 0
# new_ticker_flag = 'yes'
# #for rec in stock_df.iterrows():
# for rec in stock_df.iterrows():
#     new_ticker = stock_df['ticker']
#     new_ticker = new_ticker.iloc[i]
#     print("previous ticker and new ticker: ", prev_ticker, "and", new_ticker)
#     if (prev_ticker == new_ticker):
#         if (new_ticker_flag == 'yes'):
#             new_ticker_flag = 'no'
#             print(new_ticker_flag)
#             begin_vw = stock_df['volume_weight']
#             begin_vw = begin_vw.iloc[i]
#             print("begin_vw: ", begin_vw)
#         else:
#             last_vw = stock_df['volume_weight']
#             last_vw = last_vw.iloc[i]
#             print("last_vw: ", last_vw)
#     else:
#             print ("new")
#             vw_average = 100 - (last_vw/begin_vw) * 100
#             print("vwa: ", vw_average)
            
#             process_list.append(vw_average)
            
#             prev_ticker = new_ticker
#             new_ticker_flag == 'yes'
#             begin_vw = stock_df['volume_weight']
#             begin_vw = begin_vw.iloc[i]
#     i=i+1
# vw_average = 100 - (last_vw/begin_vw) * 100
# print("vwa: ", vw_average)
# process_list.append(vw_average)

In [8]:
# process_list

In [9]:
# ticker, to volume columns.  
#vw_average is our target

# combine object columns from stock_df with proces_list into new DataFrame process_df.
# ticker, employee_count, revenue, sector, city_name, state_name, country_code

#stock_df.columns.tolist()

In [10]:
#len(process_list)

In [11]:
#len(stock_df)

In [12]:
# make copy for testing adding process_list as column to new dataframe for model
# stock_df = stock_df.copy(deep=True)

In [13]:
stock_df = stock_df.drop(["volume_weight", "percent_change"], axis=1)
stock_df.columns.tolist()

['ticker',
 'date_val',
 'company_name',
 'company_url',
 'employee_count',
 'revenue',
 'sector',
 'city_name',
 'state_name',
 'region',
 'country_code',
 'latitude',
 'longitude',
 'open_val',
 'high_val',
 'low_val',
 'close_val',
 'volume']

In [14]:
stock_df = stock_df.drop_duplicates(subset="ticker")
stock_df.sort_values(by=["ticker"])
stock_df

,ticker,date_val,company_name,company_url,employee_count,revenue,sector,city_name,state_name,region,country_code,latitude,longitude,open_val,high_val,low_val,close_val,volume
0,AMD,2020-03-12,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,42.20,43.91,39.6000,43.90,86689681.0
504,ADBE,2020-03-12,Adobe Inc.,adobe.com,over-10k,1m-10m,Technology,San Jose,CA,W,US,37.336191,-121.890583,312.88,336.00,298.0001,335.50,8935220.0
562,AEP,2020-06-02,American Electric Power Company Inc,aep.com,over-10k,over-1b,Energy,Columbus,OH,MW,US,39.962260,-83.000707,86.31,87.96,86.1200,86.99,1898813.0
1009,ABNB,2020-12-09,Airbnb Inc,airbnb.com,5k-10k,200m-1b,Technology,San Francisco,CA,W,US,37.779026,-122.419906,146.00,165.00,141.2500,144.71,70447537.0
1324,ALGN,2020-03-12,Align Technology Inc,aligntech.com,over-10k,200m-1b,Technology,Tempe,AZ,SW,US,33.425506,-111.940009,190.00,195.97,179.0500,195.88,1240570.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48354,WBA,2020-03-12,Walgreens Boots Alliance Inc,walgreensbootsalliance.com,over-10k,over-1b,Healthcare,Chicago,IL,MW,US,41.875562,-87.624421,42.72,46.31,41.3460,46.19,11181111.0
48858,WDAY,2020-03-12,Workday Inc,workday.com,over-10k,over-1b,Technology,Pleasanton,CA,W,US,37.662431,-121.874679,137.17,140.24,125.0400,137.76,3802691.0
48866,XEL,2020-04-28,Xcel Energy Inc,my.xcelenergy.com,over-10k,over-1b,Utilities,Minneapolis,MN,MW,US,44.977300,-93.265469,67.08,67.08,64.6900,65.08,3760247.0
49866,ZM,2020-03-12,Zoom Video Communications Inc,zoom.us,1k-5k,100m-200m,Technology,San Jose,CA,W,US,37.336191,-121.890583,113.00,113.80,104.1600,107.47,9233528.0
50370,ZS,2020-03-12,Zscaler Inc,zscaler.com,1k-5k,100m-200m,Technology,San Jose,CA,W,US,37.336191,-121.890583,41.96,42.14,37.2800,41.89,3056041.0

In [15]:
stock_df.reset_index(drop=True, inplace=True)
stock_df

,ticker,date_val,company_name,company_url,employee_count,revenue,sector,city_name,state_name,region,country_code,latitude,longitude,open_val,high_val,low_val,close_val,volume
0,AMD,2020-03-12,Advanced Micro Devices Inc,amd.com,5k-10k,over-1b,Technology,Santa Clara,CA,W,US,37.233325,-121.684635,42.20,43.91,39.6000,43.90,86689681.0
1,ADBE,2020-03-12,Adobe Inc.,adobe.com,over-10k,1m-10m,Technology,San Jose,CA,W,US,37.336191,-121.890583,312.88,336.00,298.0001,335.50,8935220.0
2,AEP,2020-06-02,American Electric Power Company Inc,aep.com,over-10k,over-1b,Energy,Columbus,OH,MW,US,39.962260,-83.000707,86.31,87.96,86.1200,86.99,1898813.0
3,ABNB,2020-12-09,Airbnb Inc,airbnb.com,5k-10k,200m-1b,Technology,San Francisco,CA,W,US,37.779026,-122.419906,146.00,165.00,141.2500,144.71,70447537.0
4,ALGN,2020-03-12,Align Technology Inc,aligntech.com,over-10k,200m-1b,Technology,Tempe,AZ,SW,US,33.425506,-111.940009,190.00,195.97,179.0500,195.88,1240570.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,WBA,2020-03-12,Walgreens Boots Alliance Inc,walgreensbootsalliance.com,over-10k,over-1b,Healthcare,Chicago,IL,MW,US,41.875562,-87.624421,42.72,46.31,41.3460,46.19,11181111.0
98,WDAY,2020-03-12,Workday Inc,workday.com,over-10k,over-1b,Technology,Pleasanton,CA,W,US,37.662431,-121.874679,137.17,140.24,125.0400,137.76,3802691.0
99,XEL,2020-04-28,Xcel Energy Inc,my.xcelenergy.com,over-10k,over-1b,Utilities,Minneapolis,MN,MW,US,44.977300,-93.265469,67.08,67.08,64.6900,65.08,3760247.0
100,ZM,2020-03-12,Zoom Video Communications Inc,zoom.us,1k-5k,100m-200m,Technology,San Jose,CA,W,US,37.336191,-121.890583,113.00,113.80,104.1600,107.47,9233528.0
101,ZS,2020-03-12,Zscaler Inc,zscaler.com,1k-5k,100m-200m,Technology,San Jose,CA,W,US,37.336191,-121.890583,41.96,42.14,37.2800,41.89,3056041.0

In [16]:
stock_df.iloc[:,13:17]

     open_val  high_val   low_val  close_val
0       42.20     43.91   39.6000      43.90
1      312.88    336.00  298.0001     335.50
2       86.31     87.96   86.1200      86.99
3      146.00    165.00  141.2500     144.71
4      190.00    195.97  179.0500     195.88
..        ...       ...       ...        ...
97      42.72     46.31   41.3460      46.19
98     137.17    140.24  125.0400     137.76
99      67.08     67.08   64.6900      65.08
100    113.00    113.80  104.1600     107.47
101     41.96     42.14   37.2800      41.89

[102 rows x 4 columns]

In [17]:
stock_df.iloc[:, 16]

0       43.90
1      335.50
2       86.99
3      144.71
4      195.88
        ...
97      46.19
98     137.76
99      65.08
100    107.47
101     41.89
Name: close_val, Length: 102, dtype: float64

In [18]:
### HERE IS WHERE ISSUE LIES, length of dataframe is 102, 
### and the volume weight average from for loop list lenght is 101

# stock_df["volume_weight_avg"] = process_list

In [19]:
# stock_df.drop(columns="ticker", inplace=True)

In [20]:
# stock_df.drop(columns="city_name", inplace=True)

In [21]:
stock_cat = stock_df.dtypes[stock_df.dtypes=="object"].index.tolist()
stock_df[stock_cat].nunique()

ticker            102
company_name      102
company_url       101
employee_count      4
revenue             6
sector              9
city_name          70
state_name         28
region             11
country_code        8
dtype: int64

In [22]:
stock_df.reset_index(drop=True,inplace=True)

In [23]:
# #----------------------------------- ONE HOT ENCODE METHOD

# # Create OneHotEnocder Instance
# enc = OneHotEncoder(sparse=False)

# # Fit and transform categorical data
# encode_df = pd.DataFrame(enc.fit_transform(stock_df[stock_cat]))

# # Add the encoded variable names to encode_df
# encode_df.columns = enc.get_feature_names_out(stock_cat)
# encode_df.head()


# # -------------------------------------- OLD "BUCKETING" METHOD

#stock_df["employee_count"].astype('category').cat.codes
stock_df['employee_count'] = stock_df['employee_count'].astype('category').cat.codes
stock_df['revenue'] = stock_df['revenue'].astype('category').cat.codes
stock_df['sector'] = stock_df['sector'].astype('category').cat.codes
stock_df['region'] = stock_df['region'].astype('category').cat.codes
# stock_df['city_name'] = stock_df['city_name'].astype('category').cat.codes
# stock_df['state_name'] = stock_df['state_name'].astype('category').cat.codes
stock_df['country_code'] = stock_df['country_code'].astype('category').cat.codes

# # processing_df = stock_df.copy()

In [24]:
# # replace stock's employee count string with integer
# stock_df.loc[(stock_df['employee_count'] == '5k-10k'), 'employee_count'] = 0
# stock_df.loc[(stock_df['employee_count'] == 'over-10k'), 'employee_count'] = 1
# stock_df.loc[(stock_df['employee_count'] == '1k-5k'), 'employee_count'] = 2
# stock_df.loc[(stock_df['employee_count'] == '500-1k'), 'employee_count'] = 3

# # replace stock's revenue string with integer
# stock_df.loc[(stock_df['revenue'] == '1m-10m'), 'revenue'] = 0
# stock_df.loc[(stock_df['revenue'] == '10m-50m'), 'revenue'] = 1
# stock_df.loc[(stock_df['revenue'] == '50m-100m'), 'revenue'] = 2
# stock_df.loc[(stock_df['revenue'] == '100m-200m'), 'revenue'] = 3
# stock_df.loc[(stock_df['revenue'] == '200m-1b'), 'revenue'] = 4
# stock_df.loc[(stock_df['revenue'] == 'over-1b'), 'revenue'] = 5

# # replace stock's sector string with integer
# stock_df.loc[(stock_df['sector'] == 'Technology'), 'sector'] = 0
# stock_df.loc[(stock_df['sector'] == 'Energy'), 'sector'] = 1
# stock_df.loc[(stock_df['sector'] == 'Healthcare'), 'sector'] = 2
# stock_df.loc[(stock_df['sector'] == 'Consumer Discretionary'), 'sector'] = 3
# stock_df.loc[(stock_df['sector'] == 'Industrials'), 'sector'] = 4
# stock_df.loc[(stock_df['sector'] == 'Consumer Staples'), 'sector'] = 5
# stock_df.loc[(stock_df['sector'] == 'Communication Services'), 'sector'] = 6
# stock_df.loc[(stock_df['sector'] == 'Financials'), 'sector'] = 7
# stock_df.loc[(stock_df['sector'] == 'Utilities'), 'sector'] = 8

# # replace stock's country code string with integer (Note: China was CN and CH for some reason)
# stock_df.loc[(stock_df['country_code'] == 'US'), 'country_code'] = 0
# stock_df.loc[(stock_df['country_code'] == 'Netherlands'), 'country_code'] = 1
# stock_df.loc[(stock_df['country_code'] == 'Australia'), 'country_code'] = 2
# stock_df.loc[(stock_df['country_code'] == 'UK'), 'country_code'] = 3
# stock_df.loc[(stock_df['country_code'] == 'CH'), 'country_code'] = 4
# stock_df.loc[(stock_df['country_code'] == 'CN'), 'country_code'] = 4
# stock_df.loc[(stock_df['country_code'] == 'CA'), 'country_code'] = 5
# stock_df.loc[(stock_df['country_code'] == 'Argentina'), 'country_code'] = 6

# # replace stock's region string with integer 
# stock_df.loc[(stock_df['region'] == 'W'), 'region'] = 0
# stock_df.loc[(stock_df['region'] == 'MW'), 'region'] = 1
# stock_df.loc[(stock_df['region'] == 'SW'), 'region'] = 2
# stock_df.loc[(stock_df['region'] == 'NW'), 'region'] = 3
# stock_df.loc[(stock_df['region'] == 'SE'), 'region'] = 4
# stock_df.loc[(stock_df['region'] == 'NL'), 'region'] = 5
# stock_df.loc[(stock_df['region'] == 'AU'), 'region'] = 6
# stock_df.loc[(stock_df['region'] == 'NE'), 'region'] = 7
# stock_df.loc[(stock_df['region'] == 'GB'), 'region'] = 8
# stock_df.loc[(stock_df['region'] == 'CH'), 'region'] = 9
# stock_df.loc[(stock_df['region'] == 'CA'), 'region'] = 10


# # #create buckets for vwa
# # stock_df.loc[(stock_df['volume_weight_avg'] < 0), 'volume_weight_avg'] = 0
# # stock_df.loc[(stock_df['volume_weight_avg'] > 0) & (stock_df['volume_weight_avg'] <= 1), 'volume_weight_avg'] = 1
# # stock_df.loc[(stock_df['volume_weight_avg'] > 1) & (stock_df['volume_weight_avg'] <= 2), 'volume_weight_avg'] = 2
# # stock_df.loc[(stock_df['volume_weight_avg'] > 2) & (stock_df['volume_weight_avg'] <= 3), 'volume_weight_avg'] = 3
# # stock_df.loc[(stock_df['volume_weight_avg'] > 3) & (stock_df['volume_weight_avg'] <= 4), 'volume_weight_avg'] = 4
# # stock_df.loc[(stock_df['volume_weight_avg'] > 4) & (stock_df['volume_weight_avg'] <= 5), 'volume_weight_avg'] = 5
# # stock_df.loc[(stock_df['volume_weight_avg'] > 5) & (stock_df['volume_weight_avg'] <= 6), 'volume_weight_avg'] = 6
# # # stock_df.loc[(stock_df['volume_weight_avg'] > 6) & (stock_df['volume_weight_avg'] <= 7), 'volume_weight_avg'] = 7
# # # stock_df.loc[(stock_df['volume_weight_avg'] > 7) & (stock_df['volume_weight_avg'] <= 8), 'volume_weight_avg'] = 8
# # # stock_df.loc[(stock_df['volume_weight_avg'] > 8) & (stock_df['volume_weight_avg'] <= 9), 'volume_weight_avg'] = 9
# # # stock_df.loc[(stock_df['volume_weight_avg'] > 9) & (stock_df['volume_weight_avg'] <= 10), 'volume_weight_avg'] = 10
# # stock_df.loc[(stock_df['volume_weight_avg'] > 6), 'volume_weight_avg'] = 7

# stock_df

In [25]:
# ticker, to volume columns.  
#vw_average is our target

# combine object columns from stock_df with proces_list into new DataFrame process_df.

In [26]:
#float_stock_df = stock_df.select_dtypes(exclude=['object'])
#float_stock_df.head()

In [27]:
# Merge encode_df features and drop originals, n means new
#processing_df = encode_df.merge(stock_df, left_index=True, right_index=True) 
#processing_df = stock_df.drop(stock_cat, axis=1)
#processing_df.head()

In [28]:
# Function to run model (run each ticker and date through model in for loop)
# def random_forest(processing_df): does not need to be a functino for 'for loop' anymore
X = stock_df.iloc[:,13:17].values
#X = pd.get_dummies(X)
    
y = stock_df.iloc[:, 16]

#['percent_change'] as target

In [29]:
#X.describe()

In [30]:
np.unique(y)

array([   5.9   ,   17.2673,   19.3133,   20.78  ,   21.3   ,   23.47  ,
         23.97  ,   26.83  ,   33.76  ,   33.99  ,   34.09  ,   34.985 ,
         35.26  ,   37.64  ,   39.33  ,   39.55  ,   39.71  ,   41.89  ,
         42.28  ,   42.99  ,   43.9   ,   46.19  ,   50.89  ,   50.92  ,
         50.9767,   52.62  ,   54.43  ,   59.04  ,   60.21  ,   62.39  ,
         62.47  ,   63.98  ,   65.08  ,   65.13  ,   69.4925,   69.92  ,
         70.75  ,   71.56  ,   73.84  ,   74.7   ,   75.81  ,   77.32  ,
         82.64  ,   83.    ,   84.5   ,   85.39  ,   86.99  ,   92.83  ,
         95.54  ,   95.61  ,   97.06  ,   99.79  ,  100.29  ,  102.72  ,
        103.42  ,  107.29  ,  107.47  ,  109.324 ,  109.71  ,  110.15  ,
        115.19  ,  118.62  ,  127.45  ,  127.94  ,  129.88  ,  137.76  ,
        144.5   ,  144.71  ,  145.37  ,  145.61  ,  149.41  ,  151.57  ,
        156.9933,  158.03  ,  158.83  ,  170.28  ,  176.75  ,  182.62  ,
        195.88  ,  202.1   ,  220.86  ,  233.33  ,  234.22  ,  235.42  ,
        243.58  ,  244.02  ,  254.17  ,  256.95  ,  261.25  ,  261.78  ,
        302.27  ,  305.21  ,  335.5   ,  336.295 ,  354.3   ,  454.19  ,
        465.55  ,  535.69  , 1214.27  , 1219.73  , 1421.33  , 1785.    ])

In [31]:
# train the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [32]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [33]:
# random forest classfier
# n_estimator default at 100
random_forest = RandomForestRegressor(n_estimators=500, max_depth=15,random_state=1)
random_forest.fit(X_train, y_train)

RandomForestRegressor(max_depth=15, n_estimators=500, random_state=1)

In [34]:
y_pred = random_forest.predict(X_test)
y_true = y_test

In [35]:
errors = abs(y_pred - y_test)
mape = 100 * (errors/y_test)
accuracy = 100 - np.mean(mape)

In [36]:
print(f"r2 Score: {metrics.r2_score(y_true, y_pred)}")
print(f"mean absolute error: {metrics.mean_absolute_error(y_true, y_pred)}")
print("Accuracy:" , round(accuracy,2), '%')

r2 Score: 0.9981910780302422
mean absolute error: 4.025206246154024
Accuracy: 90.05 %

In [37]:
# print(classification_report_imbalanced(y_test, y_pred))

# with open("random_forest_result.txt", "w") as external_file:
#     add_text = classification_report_imbalanced(y_test, y_pred)
#     print(add_text, file=external_file)
#     external_file.close()

In [38]:
#sorted(zip(X.columns, random_forest.feature_importances_), reverse=True)